server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:sokoban
    username: sa
    password: 111111
autogennum:
  init-rule: asdf
